version: '3.9'

services:
  wowtogobe:
    image: wowtogobe
    container_name: WowToGoBE
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
