version: '3.9'

services:
  wowtogobe:
    image: wowtogobe
    container_name: WowToGoBE
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  postgresdb:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=25102003
      - POSTGRES_DB=WowToGoDB
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: